### ISSUE TITLE
 Max retries exceeded with url

### ISSUE THREAD

**Issue by asusman** [aussieaddons/plugin.video.nrl-live#666]
Just wondering if anyone has seen this error before? 

8:14:25.886 T:1091564288  NOTICE: [NRL Live v1.3.0] Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.nrl-live/resources/lib/play.py", line 32, in play_video
                                                playlist = ooyalahelper.get_m3u8_playlist(video_id, pcode, live)
                                              File "/home/osmc/.kodi/addons/plugin.video.nrl-live/resources/lib/ooyalahelper.py", line 213, in get_m3u8_playlist
                                                login_ticket = get_user_ticket()
                                              File "/home/osmc/.kodi/addons/plugin.video.nrl-live/resources/lib/ooyalahelper.py", line 50, in get_user_ticket
                                                telstra_password)
                                              File "/home/osmc/.kodi/addons/plugin.video.nrl-live/resources/lib/telstra_auth.py", line 130, in get_free_token
                                                sso_token_resp = session.get(sso_url)
                                              File "/home/osmc/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 521, in get
                                                return self.request('GET', url, **kwargs)
                                              File "/home/osmc/.kodi/addons/script.module.aussieaddonscommon/lib/aussieaddonscommon/session.py", line 60, in request
                                                raise AussieAddonsException('Error: {0}'.format(e))
                                            AussieAddonsException: Error: HTTPSConnectionPool(host='api.telstra.com', port=443): Max retries exceeded with url: /v1/sso/idpcallback?cbs=eyJhbGciOiJIUzI1NiJ9.eyJjYWxsYmFja19zdGF0ZSI6IjM3NGU2YjcyLWQ2MDMtNDExYy05Njg2LWI5ZmZjMTI1OWIyZCIsImF1ZCI6InJhYSIsImV4cCI6MTUyMDgzODg2MjY5MCwiaWF0IjoxNTIwNzUyNDYyNjkwfQ.ez_K3nRmOqnDYUEIjsnYxBAMTnOnwdHca-drEy6_uDM&app_name=One%20Place%20portal (Caused by ResponseError('too many 500 error responses',))

**Comment by glennguy** [comment]
Nope! The code for this part of the addon is effectively brand new as of today, so there's potentially some bugs and edge cases to get sorted.

As for your particular error the fault could lay with Telstra, you, or me. It could be an incorrect username or password as there's nothing in the code yet to catch when that happens and give the right feedback to the user. Or an issue with Telstra's server, like being overloaded from everyone trying to activate their live passes in round 1.

You have the addon set for the free live pass, make sure that your phone number is attached to your Telstra ID account. You can check your ID is set up right in a desktop browser - https://hub.telstra.com.au/sp2017-afl-app.html?device=desktop#

If you're still having no luck, a good workaround is setting up an nrl.com account in the app and linking your live pass. Then you can change to the nrl.com setting and get up and running that way.

**Comment by asusman** [comment]
Thanks Glen appreciate your reply. 

We can close this issue. I managed to get it working and the problem was a DNS issue. I use getflix and moving to different DNS servers (non getflix) resolved the issue. I suspect they be blocking them or my DNS channel groups are configured incorrectly.

**Comment by glennguy** [comment]
That's great to know, thanks for the info.
